# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title:            knolleary
tagline:          "Things by Nick O'Leary"
description:      'Words and things by Nick O&apos;Leary.'
baseurl:          /

author:
  name:           "Nick O'Leary"
  url:            https://twitter.com/knolleary
  twitter:        "@knolleary"

plugins:
    - jekyll-paginate
    - jekyll-redirect-from
